require "relation_to_struct/version"
require "relation_to_struct/active_record_connection_adapter_extension"
require "relation_to_struct/active_record_base_extension"
require "relation_to_struct/active_record_relation_extension"
