require "relation_to_struct/version"
require "relation_to_struct/active_record_base_extension"
require "relation_to_struct/active_record_relation_extension"
require "relation_to_struct/active_record_result_41_extension"

module RelationToStruct
end
